### ISSUE TITLE
Detection doesnt work properly

### ISSUE THREAD

**Issue by kleozzy** [NImaism/takeit#1]
I have a url thats redirected to postman pages , CNAME points to postman but your tool detects it as AWS bucket vulnerable. 

I have also checked DNS and page source manually , there no AWS bucket text or hosts anywhere.

**Comment by NImaism** [comment]
Hello @kleozzy,

Thank you for your message. I have reviewed the code, and it appears to be functioning correctly. Could you please provide your URL so we can investigate further?

**Comment by kleozzy** [comment]
Sure try with : postman.backblaze.com

**Comment by TheeEclipse** [comment]
Seems to work fine

**Comment by kleozzy** [comment]
Thats not aws bucket

**Comment by TheeEclipse** [comment]
share exact  console output if you don't mind

**Comment by NImaism** [comment]
**Takeit** based on [can-i-take-over-xyz](https://github.com/EdOverflow/can-i-take-over-xyz/). It identifies URLs as vulnerable if they contain specific fingerprints associated with takeover risks. In your case, the URL includes the message `"The specified bucket does not exist: NonExistentBucket"` which matches one of these fingerprints. This is why my tool flagged it as potentially vulnerable. I will soon be adding the capability to match CNAME records from [can-i-take-over-xyz](https://github.com/EdOverflow/can-i-take-over-xyz/) as well.

**Comment by NImaism** [comment]
Also you can utilize the exclude pattern feature in the tool to avoid **false** positives, please refer to the "README" file in the repository. There are specific instructions and examples provided there to help you set it up effectively.

**Comment by kleozzy** [comment]
i see , the final page is a docs site and it indeed has this text , i guess it hard to filter those false positives out:

![image](https://github.com/user-attachments/assets/2e67b9b1-2396-43e0-8ce6-42c080f55473)

**Comment by NImaism** [comment]
It's **not** too hard to fix, and I'll work on reducing the false positives.

**Comment by kleozzy** [comment]
That would be awesome.
